<a href="https://colab.research.google.com/github/sheCodesAI/ML-handsOn-workbook/blob/main/DesicionTree_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
df = pd.read_csv("/content/salaries (2).csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [8]:
 inputs = df.drop('salary_more_then_100k',axis='columns')
 target = df['salary_more_then_100k']
 inputs

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [9]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
# Converts text → numbers

In [11]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

ex : create a new encoder(converter) for company column

In [12]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_company.fit_transform(inputs['job'])
inputs['degree_n'] = le_company.fit_transform(inputs['degree'])
inputs.head()

  company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

👉 Take company column
👉 Convert text → numbers
👉 Store in new column company_n

fit_transform 👉 do 2 things:

learn text values

convert into numbers

In [13]:
# drop those label cols
inputs_n = inputs.drop(['company', 'job', 'degree'], axis='columns')
inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

train our classifier now

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(inputs_n, target, test_size=0.2)

In [16]:
len(x_train)

12

In [17]:
len(x_test)

4

In [18]:
len(y_train)

12

In [19]:
len(y_test)

4

In [20]:
x_train

    company_n  job_n  degree_n
3           2      0         1
9           0      0         1
10          1      2         0
6           0      2         1
0           2      2         0
11          1      2         1
14          1      1         0
8           0      0         0
4           2      1         0
7           0      1         0
2           2      0         0
5           2      1         1

In [21]:
x_test

    company_n  job_n  degree_n
12          1      0         0
1           2      2         1
15          1      1         1
13          1      0         1

# ***Ready to train our classifier***

In [22]:
from sklearn import tree

In [23]:
model = tree.DecisionTreeClassifier()

In [24]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [25]:
model.score(inputs_n, target)

1.0

In [26]:
model.predict([[2,2,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [27]:
prediction_input = pd.DataFrame([[2, 2, 1]], columns=['company_n', 'job_n', 'degree_n'])

# Now, predict using this DataFrame
model.predict(prediction_input)

array([0])

***just for my practice***

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression()

In [31]:
model.fit(x_train, y_train)

LinearRegression()

In [32]:
model.predict(x_test)

array([0.52822581, 0.85241935, 0.8       , 0.925     ])

In [33]:
model.score(x_test, y_test)

-0.32641952826916376