<a href="https://colab.research.google.com/github/sheCodesAI/ML_mini_models/blob/main/multiVariateRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [43]:
df = pd.read_csv("/content/house_prices_multi.csv")

In [44]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

above data looks like linear

# **Topics**
- ### Data Processing: Handling NA values
- ### Linear Resgression using Multiple Variables
: Instead of 1 input → you use multiple inputs
Example:
Area 🏠
Bedrooms 🛏️
Age ⏳

👉 All together predict Price 💰
---

👉 b = just numbers (coefficients)

👉 They are not in your data table ❌

👉 They are created by ML ✅

## **y=b0​+b1​x1​+b2​x2​+b3​x3​**

🔵 Dots = your real data points

📈 Line = ML’s prediction line
(this is created using b values)

ML finds best b → best line → best prediction

In [45]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

# handle missing value by taking median

In [46]:
df.bedrooms.median()

3.5

In [47]:
df.fillna(3.5, inplace = True)

In [48]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.5   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

before apply any ml models,
do preprocess and clean

In [49]:
model = linear_model.LinearRegression()
model.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [50]:
model.coef_
# means check wt values ML predicted to b

array([    198.47159002, -116583.73881651,  -14267.77585936])

In [51]:
model.intercept_

np.float64(656046.539004866)

In [52]:
model.predict([[4000,4,30]])
# here we predicted price, by passing area, bedrooms, old_age

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([555564.668027])

### **how it calculated the prev price?**

In [53]:
model.coef_

array([    198.47159002, -116583.73881651,  -14267.77585936])

In [54]:
198.47*4000 + -116583*4 + -14267*30 + 656046.539

555584.539

we used formula here

y=b0​+b1​x1​+b2​x2​+b3​x3​

where b are the values predicted by ML, check val : model_coef_